/**
 * Terraform (7.1): manage servers, tenants and API keys of a (control-plane) gateway with Terraform.
 *
 * A REST resource API shaped for the generic [`Mastercard/restapi`](https://registry.terraform.io/providers/Mastercard/restapi)
 * provider (`restapi_object`: `POST` creates, `GET`/`PUT`/`DELETE` on `<path>/<id>`), plus an HCL export of the running
 * config with `import` blocks, so an existing gateway can be adopted by Terraform in one `terraform apply`.
 *
 * - `GET    /admin/terraform` — kinds, paths and the provider block to use.
 * - `GET    /admin/terraform/:kind` — `servers` (id), `tenants` (id), `apiKeys` (name; object-form keys with a `name`).
 * - `POST   /admin/terraform/:kind[?dryRun=true]` — create (409 when the id exists).
 * - `GET    /admin/terraform/:kind/:id` — one object (secrets `<redacted>`, `ETag`).
 * - `PUT    /admin/terraform/:kind/:id[?dryRun=true]` — replace (`If-Match` → 412 on a stale ETag; `<redacted>` keeps the value).
 * - `DELETE /admin/terraform/:kind/:id` — remove (`If-Match` honoured).
 * - `GET    /admin/terraform/export[?format=hcl|json][&url=]` — `main.tf` for the running config (secrets become sensitive variables).
 *
 * Every write validates the whole resulting config and hot-applies it (like `PUT /admin/config`); writes need
 * `controlPlane.configApi: true`. Changes live in the running config — keep Terraform as the source of truth.
 *
 * @module features/terraform
 */

import type { Request, Response, Router } from 'express';
import { registerFeature, objectBody, badRequest, type FeatureContext } from '../gateway/features.js';
import { portableConfig } from '../gateway/admin.js';
import { configEtag } from '../gateway/control-plane.js';
import { REDACTED, redactConfig, restoreRedacted } from '../config/diff.js';

type Obj = Record<string, unknown>;

export interface ResourceKind {
  /** Field that identifies an object. */
  idField: 'id' | 'name';
  /** Terraform resource-name prefix. */
  prefix: string;
  list: (cfg: Obj) => Obj[];
  /** Returns the config with `items` in place of the kind's objects (non-addressable entries are kept). */
  set: (cfg: Obj, items: Obj[]) => Obj;
}

const isObj = (v: unknown): v is Obj => !!v && typeof v === 'object' && !Array.isArray(v);

export const KINDS: Record<string, ResourceKind> = {
  servers: {
    idField: 'id',
    prefix: 'server',
    list: (c) => ((c.servers as unknown[]) ?? []).filter(isObj),
    set: (c, items) => ({ ...c, servers: items }),
  },
  tenants: {
    idField: 'id',
    prefix: 'tenant',
    list: (c) => ((c.tenants as unknown[]) ?? []).filter(isObj),
    set: (c, items) => {
      const { tenants: _t, ...rest } = c;
      return items.length ? { ...rest, tenants: items } : rest;
    },
  },
  apiKeys: {
    idField: 'name',
    prefix: 'api_key',
    list: (c) => (((c.auth as Obj | undefined)?.apiKeys as unknown[]) ?? []).filter((k): k is Obj => isObj(k) && typeof k.name === 'string'),
    set: (c, items) => {
      const auth = (c.auth as Obj | undefined) ?? {};
      const unnamed = ((auth.apiKeys as unknown[]) ?? []).filter((k) => !(isObj(k) && typeof k.name === 'string'));
      return { ...c, auth: { ...auth, apiKeys: [...unnamed, ...items] } };
    },
  },
};

const tfName = (prefix: string, id: string) => `${prefix}_${id.replace(/[^A-Za-z0-9_-]/g, '_')}`.replace(/^([^A-Za-z_])/, '_$1');
const hclKey = (k: string) => (/^[A-Za-z_][A-Za-z0-9_-]*$/.test(k) ? k : JSON.stringify(k));
const hclString = (s: string) => JSON.stringify(s).replace(/\$\{/g, '$$$${').replace(/%\{/g, '%%{');

/** Render a JSON value as an HCL expression; `secret(path)` returns a variable name for `<redacted>` strings. */
export function toHcl(v: unknown, indent = '', secret?: (path: string[]) => string, path: string[] = []): string {
  if (v === REDACTED && secret) return `var.${secret(path)}`;
  if (typeof v === 'string') return hclString(v);
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (v === null || v === undefined) return 'null';
  const inner = indent + '  ';
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    return `[\n${v.map((x, i) => `${inner}${toHcl(x, inner, secret, [...path, String(i)])},`).join('\n')}\n${indent}]`;
  }
  const entries = Object.entries(v as Obj).filter(([, x]) => x !== undefined);
  if (!entries.length) return '{}';
  return `{\n${entries.map(([k, x]) => `${inner}${hclKey(k)} = ${toHcl(x, inner, secret, [...path, k])}`).join('\n')}\n${indent}}`;
}

const SECRET_FIELDS: Record<string, string[]> = { servers: ['headers', 'env'], tenants: [], apiKeys: ['key'] };

/** `main.tf` (restapi provider + one `restapi_object` and `import` block per object) for a config in schema form. */
export function exportHcl(cfg: Obj, baseUrl = 'http://localhost:4000'): string {
  const vars: string[] = [];
  const out: string[] = [
    '# Generated by mcp-gateway (GET /api/v1/admin/terraform/export).',
    'terraform {',
    '  required_providers {',
    '    restapi = { source = "Mastercard/restapi", version = "~> 1.19" }',
    '  }',
    '}',
    '',
    'variable "gateway_url" {',
    '  type    = string',
    `  default = ${hclString(baseUrl)}`,
    '}',
    '',
    'variable "gateway_admin_key" {',
    '  type      = string',
    '  sensitive = true',
    '}',
    '',
    'provider "restapi" {',
    '  uri                  = var.gateway_url',
    '  write_returns_object = true',
    '  headers              = { Authorization = "Bearer ${var.gateway_admin_key}" }',
    '}',
  ];
  for (const [kind, k] of Object.entries(KINDS)) {
    for (const obj of k.list(cfg)) {
      const id = String(obj[k.idField]);
      const name = tfName(k.prefix, id);
      const secret = (path: string[]) => {
        const v = `${name}_${path.join('_')}`.replace(/[^A-Za-z0-9_]/g, '_');
        if (!vars.includes(v)) vars.push(v);
        return v;
      };
      const ignore = SECRET_FIELDS[kind]!.filter((f) => obj[f] !== undefined);
      out.push(
        '',
        `resource "restapi_object" ${hclString(name)} {`,
        `  path         = "/api/v1/admin/terraform/${kind}"`,
        `  id_attribute = "${k.idField}"`,
        `  data         = jsonencode(${toHcl(redactConfig(obj), '  ', secret)})`,
        ...(ignore.length ? [`  ignore_changes_to = ${JSON.stringify(ignore)}`] : []),
        '}',
        '',
        'import {',
        `  to = restapi_object.${name}`,
        `  id = ${hclString(`/api/v1/admin/terraform/${kind}/${id}`)}`,
        '}',
      );
    }
  }
  for (const v of vars) out.push('', `variable "${v}" {`, '  type      = string', '  sensitive = true', '}');
  return out.join('\n') + '\n';
}

function mount(router: Router, ctx: FeatureContext): void {
  const current = () => portableConfig(ctx.config());
  const kindOf = (req: Request, res: Response): ResourceKind | undefined => {
    const k = KINDS[String(req.params.kind)];
    if (!k) res.status(404).json({ error: 'Not Found', message: `Unknown kind "${req.params.kind}" (${Object.keys(KINDS).join(', ')})` });
    return k;
  };
  const writable = (res: Response): boolean => {
    if (ctx.config().controlPlane?.configApi !== true) {
      res.status(403).json({ error: 'Forbidden', message: 'Terraform writes need controlPlane.configApi: true' });
      return false;
    }
    if (!ctx.applyConfig) {
      res.status(501).json({ error: 'Not Implemented', message: 'This gateway cannot apply config changes' });
      return false;
    }
    return true;
  };
  const apply = async (req: Request, res: Response, next: Obj, status: number, body: unknown) => {
    const dryRun = req.query.dryRun === 'true';
    try {
      const { changes } = await ctx.applyConfig!(next, dryRun);
      if (dryRun) return void res.json({ dryRun: true, changes });
      if (body === undefined) return void res.status(204).end();
      res.status(status).set('ETag', configEtag(body)).json(redactConfig(body));
    } catch (err) {
      badRequest(res, err instanceof Error ? err.message : String(err));
    }
  };
  const preconditionFailed = (req: Request, res: Response, obj: Obj): boolean => {
    const im = req.get('if-match');
    if (im && im !== '*' && !im.split(',').map((s) => s.trim()).includes(configEtag(obj))) {
      res.status(412).json({ error: 'Precondition Failed', message: 'The object changed since it was read (ETag mismatch)' });
      return true;
    }
    return false;
  };

  router.get('/', (_req, res) => {
    res.json({
      provider: { source: 'Mastercard/restapi', version: '~> 1.19' },
      kinds: Object.entries(KINDS).map(([kind, k]) => ({ kind, path: `/api/v1/admin/terraform/${kind}`, idAttribute: k.idField })),
      export: '/api/v1/admin/terraform/export',
      writable: ctx.config().controlPlane?.configApi === true,
    });
  });

  router.get('/export', (req, res) => {
    const cfg = current();
    if (req.query.format === 'json') {
      return void res.json(Object.fromEntries(Object.entries(KINDS).map(([kind, k]) => [kind, k.list(cfg).map((o) => redactConfig(o))])));
    }
    const url = typeof req.query.url === 'string' && /^https?:\/\//.test(req.query.url) ? req.query.url : ctx.baseUrl() ?? undefined;
    res.type('text/plain').set('Content-Disposition', 'inline; filename="main.tf"').send(exportHcl(cfg, url));
  });

  router.get('/:kind', (req, res) => {
    const k = kindOf(req, res);
    if (!k) return;
    res.json({ kind: req.params.kind, items: k.list(current()).map((o) => redactConfig(o)) });
  });

  router.get('/:kind/:id', (req, res) => {
    const k = kindOf(req, res);
    if (!k) return;
    const obj = k.list(current()).find((o) => o[k.idField] === req.params.id);
    if (!obj) return void res.status(404).json({ error: 'Not Found', message: `No ${req.params.kind} "${req.params.id}"` });
    res.set('ETag', configEtag(obj)).json(redactConfig(obj));
  });

  router.post('/:kind', async (req, res) => {
    const k = kindOf(req, res);
    if (!k || !writable(res)) return;
    const b = objectBody(req, res);
    if (!b) return;
    const id = b[k.idField];
    if (typeof id !== 'string' || !id) return badRequest(res, `Body needs a string "${k.idField}"`);
    const cfg = current();
    if (req.params.kind === 'apiKeys' && (cfg.auth as Obj | undefined)?.strategy !== 'api-key') {
      return void res.status(409).json({ error: 'Conflict', message: 'API keys need auth.strategy: api-key' });
    }
    const items = k.list(cfg);
    if (items.some((o) => o[k.idField] === id)) return void res.status(409).json({ error: 'Conflict', message: `${req.params.kind} "${id}" already exists` });
    await apply(req, res, k.set(cfg, [...items, b]), 201, b);
  });

  router.put('/:kind/:id', async (req, res) => {
    const k = kindOf(req, res);
    if (!k || !writable(res)) return;
    const b = objectBody(req, res);
    if (!b) return;
    const cfg = current();
    const items = k.list(cfg);
    const i = items.findIndex((o) => o[k.idField] === req.params.id);
    if (i < 0) return void res.status(404).json({ error: 'Not Found', message: `No ${req.params.kind} "${req.params.id}"` });
    if (b[k.idField] !== undefined && b[k.idField] !== req.params.id) return badRequest(res, `"${k.idField}" cannot change (delete and create instead)`);
    if (preconditionFailed(req, res, items[i]!)) return;
    const obj = restoreRedacted({ ...b, [k.idField]: req.params.id }, items[i]) as Obj;
    const next = items.slice();
    next[i] = obj;
    await apply(req, res, k.set(cfg, next), 200, obj);
  });

  router.delete('/:kind/:id', async (req, res) => {
    const k = kindOf(req, res);
    if (!k || !writable(res)) return;
    const cfg = current();
    const items = k.list(cfg);
    const obj = items.find((o) => o[k.idField] === req.params.id);
    if (!obj) return void res.status(404).json({ error: 'Not Found', message: `No ${req.params.kind} "${req.params.id}"` });
    if (preconditionFailed(req, res, obj)) return;
    await apply(req, res, k.set(cfg, items.filter((o) => o !== obj)), 204, undefined);
  });
}

registerFeature({
  id: 'terraform',
  since: '7.1.0',
  summary: 'Terraform: REST resources for servers, tenants and API keys (restapi provider) and HCL export with import blocks',
  mount,
});
