{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-gateway.apiKeysSecret" . }}
  labels: {{- include "mcp-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  MCP_GATEWAY_API_KEYS: {{ join "," .Values.apiKeys | quote }}
{{- end }}
